{
  inputs,
  lib,
  ...
} @ top: {
  imports = [inputs.flake-file.flakeModules.default];

  flake-file = {
    do-not-edit = ''
      # DO NOT EDIT!
      # Auto-generated by `nix run .#write-flake` from flake-file
      # The main outputs are in ./modules/outputs.nix
      # The static part is defined at ./modules/flake-file.nix
    '';

    formatter = pkgs: pkgs.alejandra;

    inputs = lib.mkMerge ([
        {
          nix-packages.url = "github:thou-vow/nix-packages";
        }
      ]
      ++ map (k: {${k}.follows = "nix-packages/${k}";}) [
        "determinate"
        "determinate-nix"
        "flake-file"
        "flake-parts"
        "home-manager"
        "impermanence"
        "import-tree"
        "nix-index-database"
        "nix-on-droid"
        "nix-wrapper-modules"
        "nixpkgs"
        "nixpkgs-nod"
        "nixpkgs-stable"
        "nyx-loner"
        "treefmt-nix"
      ]);

    nixConfig = lib.pipe top.config.substituters [
      builtins.attrValues
      (map ({
        keys,
        urls,
      }: {
        extra-substituters = urls;
        extra-trusted-public-keys = keys;
      }))
      lib.mkMerge
    ];

    outputs =
      # nix
      ''inputs: inputs.flake-parts.lib.mkFlake {inherit inputs;} (inputs.import-tree ./modules)'';

    style.sep = {
      flake = "\n\n/*\nDo not edit\n*/\n";
      inputs = "\n/*\nDo not edit\n*/\n";
    };
  };

  substituters = {
    nix-community = {
      urls = ["https://nix-community.cachix.org"];
      keys = ["nix-community.cachix.org-1:mB9FSh9qf2dCimDSUo8Zy7bkq5CX+/rkCWyvRCYg3Fs="];
    };
    nix-on-droid = {
      urls = ["https://nix-on-droid.cachix.org"];
      keys = ["nix-on-droid.cachix.org-1:56snoMJTXmDRC1Ei24CmKoUqvHJ9XCp+nidK7qkMQrU="];
    };
    nyx-loner = {
      urls = ["https://cache.garnix.io"];
      keys = ["cache.garnix.io:CTFPyKSLcx5RMJKfLo5EEPUObbA78b0YQ2DTCJXqr9g="];
    };
    thou-vow = {
      urls = ["https://thou-vow.cachix.org"];
      keys = ["thou-vow.cachix.org-1:n6zUvWYOI7kh0jgd+ghWhxeMd9tVdYF2KdOvufJ/Qy4="];
    };
  };
}
