# DO NOT EDIT!
# Auto-generated by nix run .#write-flake from flake-file
# The outputs are in ./modules/outputs.nix
# The static part is defined at ./modules/flake-file.nix
{
  outputs = inputs: inputs.flake-parts.lib.mkFlake {inherit inputs;} (inputs.import-tree ./modules);

  nixConfig = {
    extra-substituters = ["https://thou-vow.cachix.org" "https://cache.garnix.io" "https://nix-on-droid.cachix.org" "https://nix-community.cachix.org"];
    extra-trusted-public-keys = ["thou-vow.cachix.org-1:n6zUvWYOI7kh0jgd+ghWhxeMd9tVdYF2KdOvufJ/Qy4=" "cache.garnix.io:CTFPyKSLcx5RMJKfLo5EEPUObbA78b0YQ2DTCJXqr9g=" "nix-on-droid.cachix.org-1:56snoMJTXmDRC1Ei24CmKoUqvHJ9XCp+nidK7qkMQrU=" "nix-community.cachix.org-1:mB9FSh9qf2dCimDSUo8Zy7bkq5CX+/rkCWyvRCYg3Fs="];
  };

  inputs = {
    determinate = {
      url = "github:DeterminateSystems/determinate";
      inputs.nix.inputs = {
        nixpkgs-23-11.follows = "nixpkgs";
        nixpkgs-regression.follows = "nixpkgs";
      };
    };
    determinate-nix.follows = "determinate/nix";
    flake-file.follows = "nix-packages/flake-file";
    flake-parts.follows = "nix-packages/flake-parts";
    home-manager = {
      url = "github:nix-community/home-manager";
      inputs.nixpkgs.follows = "nixpkgs";
    };
    impermanence = {
      url = "github:nix-community/impermanence";
      inputs = {
        home-manager.follows = "home-manager";
        nixpkgs.follows = "nixpkgs";
      };
    };
    import-tree.follows = "nix-packages/import-tree";
    nix-index-database = {
      url = "github:nix-community/nix-index-database";
      inputs.nixpkgs.follows = "nixpkgs";
    };
    nix-on-droid = {
      url = "github:nix-community/nix-on-droid";
      inputs = {
        home-manager.follows = "home-manager";
        nixpkgs.follows = "nixpkgs";
      };
    };
    nix-packages.url = "github:thou-vow/nix-packages";
    nix-wrapper-modules = {
      url = "github:BirdeeHub/nix-wrapper-modules";
      inputs.nixpkgs.follows = "nixpkgs";
    };
    nixpkgs.follows = "nix-packages/nixpkgs";
    nixpkgs-nod.url = "github:NixOS/nixpkgs/88d3861acdd3d2f0e361767018218e51810df8a1";
    nixpkgs-stable.url = "github:NixOS/nixpkgs/nixos-25.11";
    nyx-loner = {
      url = "github:lonerOrz/nyx-loner";
      inputs.home-manager.follows = "home-manager";
    };
    treefmt-nix.follows = "nix-packages/treefmt-nix";
  };
}
