# DO NOT EDIT!
# Auto-generated by `nix run .#write-flake` from flake-file
# The main outputs are in ./modules/outputs.nix
# The static part is defined at ./modules/flake-file.nix
{
  outputs = inputs: inputs.flake-parts.lib.mkFlake {inherit inputs;} (inputs.import-tree ./modules);

  /*
  Do not edit
  */
  nixConfig = {
    extra-substituters = ["https://thou-vow.cachix.org" "https://cache.garnix.io" "https://nix-on-droid.cachix.org" "https://nix-community.cachix.org"];
    extra-trusted-public-keys = ["thou-vow.cachix.org-1:n6zUvWYOI7kh0jgd+ghWhxeMd9tVdYF2KdOvufJ/Qy4=" "cache.garnix.io:CTFPyKSLcx5RMJKfLo5EEPUObbA78b0YQ2DTCJXqr9g=" "nix-on-droid.cachix.org-1:56snoMJTXmDRC1Ei24CmKoUqvHJ9XCp+nidK7qkMQrU=" "nix-community.cachix.org-1:mB9FSh9qf2dCimDSUo8Zy7bkq5CX+/rkCWyvRCYg3Fs="];
  };

  /*
  Do not edit
  */
  inputs = {
    determinate.follows = "nix-packages/determinate";
    /*
    Do not edit
    */
    determinate-nix.follows = "nix-packages/determinate-nix";
    /*
    Do not edit
    */
    flake-file.follows = "nix-packages/flake-file";
    /*
    Do not edit
    */
    flake-parts.follows = "nix-packages/flake-parts";
    /*
    Do not edit
    */
    home-manager.follows = "nix-packages/home-manager";
    /*
    Do not edit
    */
    impermanence.follows = "nix-packages/impermanence";
    /*
    Do not edit
    */
    import-tree.follows = "nix-packages/import-tree";
    /*
    Do not edit
    */
    nix-index-database.follows = "nix-packages/nix-index-database";
    /*
    Do not edit
    */
    nix-on-droid.follows = "nix-packages/nix-on-droid";
    /*
    Do not edit
    */
    nix-packages.url = "github:thou-vow/nix-packages";
    /*
    Do not edit
    */
    nix-wrapper-modules.follows = "nix-packages/nix-wrapper-modules";
    /*
    Do not edit
    */
    nixpkgs.follows = "nix-packages/nixpkgs";
    /*
    Do not edit
    */
    nixpkgs-nod.follows = "nix-packages/nixpkgs-nod";
    /*
    Do not edit
    */
    nixpkgs-stable.follows = "nix-packages/nixpkgs-stable";
    /*
    Do not edit
    */
    nyx-loner.follows = "nix-packages/nyx-loner";
    /*
    Do not edit
    */
    treefmt-nix.follows = "nix-packages/treefmt-nix";
  };
}
