[determinate]
src.git = "https://github.com/DeterminateSystems/determinate"
fetch.github = "DeterminateSystems/determinate"

[jail-nix]
src.git = "https://git.sr.ht/~alexdavid/jail.nix"
fetch.git = "https://git.sr.ht/~alexdavid/jail.nix"

[preservation]
src.git = "https://github.com/nix-community/preservation"
fetch.github = "nix-community/preservation"

[treefmt-nix]
src.git = "https://github.com/numtide/treefmt-nix"
fetch.github = "numtide/treefmt-nix"
