exec-once=waybar

allow_tearing=2

repeat_rate=60
repeat_delay=200
numlockon=1
xkb_rules_model=thinkpad
xkb_rules_layout=br,us
xkb_rules_options=caps:escape_shifted_capslock,grp:win_space_toggle

trackpad_natural_scrolling=1
trackpad_accel_speed=0.4
click_method=2

borderpx=1
gappih=3
gappiv=2
gappoh=6
gappov=4

sloppyfocus=0

rootcolor=0x060810ff
bordercolor=0x0d111bff
focuscolor=0xf4dbe2ff
urgentcolor=0xf6cba9ff
maximizescreencolor=0xdaccf6ff

blur=1

shadows=1
shadowscolor=0x060810ff

border_radius=3

animation_duration_move=250
animation_duration_open=200
animation_duration_tag=150
animation_duration_close=150

tag_animation_direction=0

scroller_default_proportion=0.6

new_is_master=0

tagrule=id:1,layout_name:scroller

bindl=NONE,XF86AudioMicMute,spawn,wpctl set-mute @DEFAULT_AUDIO_SOURCE@ toggle
bindl=NONE,XF86AudioMute,spawn,wpctl set-mute @DEFAULT_AUDIO_SINK@ toggle
bindl=NONE,XF86AudioLowerVolume,spawn,wpctl set-volume @DEFAULT_AUDIO_SINK@ 0.01-
bindl=NONE,XF86AudioRaiseVolume,spawn,wpctl set-volume @DEFAULT_AUDIO_SINK@ 0.01+
bind=NONE,XF86AudioNext,spawn,playerctl next
bind=NONE,XF86AudioPrev,spawn,playerctl previous
bind=NONE,XF86AudioPlay,spawn,playerctl play-pause
bindl=NONE,XF86MonBrightnessDown,spawn,brightnessctl set 1%-
bindl=NONE,XF86MonBrightnessUp,spawn,brightnessctl set 1%+

bind=SUPER,F5,reload_config
bind=NONE,Print,spawn,flameshot gui
bind=SUPER+SHIFT,End,quit
bind=SUPER,Minus,resizewin,-10,0
bind=SUPER+SHIFT,Minus,resizewin,0,-10
bind=SUPER,Equal,resizewin,+10,0
bind=SUPER+SHIFT,Equal,resizewin,0,+10

bind=SUPER,Q,killclient,
bind=SUPER+SHIFT,Q,killclient,force
bind=SUPER,W,spawn,dash -c $BROWSER
bind=SUPER,T,spawn,dash -c $TERMINAL
bind=SUPER,P,viewtoleft,0
bind=SUPER+SHIFT,P,tagtoleft,0

bind=SUPER,H,focusdir,left
bind=SUPER+SHIFT,H,exchange_client,left
bind=SUPER+CTRL,H,scroller_stack,left
bind=SUPER,J,focusdir,down
bind=SUPER+SHIFT,J,exchange_client,down
bind=SUPER+CTRL,J,scroller_stack,down
bind=SUPER,K,focusdir,up
bind=SUPER+SHIFT,K,exchange_client,up
bind=SUPER+CTRL,K,scroller_stack,up
bind=SUPER,L,focusdir,right
bind=SUPER+SHIFT,L,exchange_client,right
bind=SUPER+CTRL,L,scroller_stack,right

bind=SUPER,Z,togglemaximizescreen
bind=SUPER+SHIFT,Z,togglefullscreen
bind=SUPER,N,viewtoright,0
bind=SUPER+SHIFT,N,tagtoright,0
bind=SUPER,Return,spawn,fuzzel

