# This file was generated by nvfetcher, please do not modify it manually.
{
  fetchgit,
  fetchurl,
  fetchzip,
  fetchFromGitHub,
  dockerTools,
}:
{
  determinate = {
    pname = "determinate";
    version = "efa5aa3cc1a40cf3dab8c07bfbc07f5edd44d4a6";
    src = fetchFromGitHub {
      owner = "DeterminateSystems";
      repo = "determinate";
      rev = "efa5aa3cc1a40cf3dab8c07bfbc07f5edd44d4a6";
      fetchSubmodules = false;
      sha256 = "sha256-hhPxK9t1ofQnId9vcrtW2C7sC+fB6EJx6Q7RtqUAtKo=";
    };
    date = "2026-05-29";
  };
  jail-nix = {
    pname = "jail-nix";
    version = "42b355c38ca63dab4904acc5c0d95f17954a8c9b";
    src = fetchgit {
      url = "https://git.sr.ht/~alexdavid/jail.nix";
      rev = "42b355c38ca63dab4904acc5c0d95f17954a8c9b";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sparseCheckout = [ ];
      sha256 = "sha256-h4MGNbOo7L3RHi4uNFmsg5g17/DHXEfnv/xiG6BrNFQ=";
    };
    date = "2026-02-26";
  };
  preservation = {
    pname = "preservation";
    version = "93416f4614ad2dfed5b0dcf12f27e57d27a5ab11";
    src = fetchFromGitHub {
      owner = "nix-community";
      repo = "preservation";
      rev = "93416f4614ad2dfed5b0dcf12f27e57d27a5ab11";
      fetchSubmodules = false;
      sha256 = "sha256-mMI9IanU+Xw+pVogD2oT0I2kTmvz2Un/Apc5+CwUpEY=";
    };
    date = "2025-09-09";
  };
  treefmt-nix = {
    pname = "treefmt-nix";
    version = "db947814a175b7ca6ded66e21383d938df01c227";
    src = fetchFromGitHub {
      owner = "numtide";
      repo = "treefmt-nix";
      rev = "db947814a175b7ca6ded66e21383d938df01c227";
      fetchSubmodules = false;
      sha256 = "sha256-eynAfOmbmxJnkp7YewvCEbShNnnYJ9gLLqkzsYtBPeM=";
    };
    date = "2026-05-31";
  };
}
