(require-builtin helix/core/keymaps as hx.core.keymaps.)
(require (prefix-in hx.cfg. "helix/configuration.scm"))
(require "self/utils.scm")

(define (normal->select value)
  (define command-map
    (kv (ls "select_mode" "exit_select_mode")
      (ls "move_char_left" "extend_char_left")
      (ls "move_visual_line_down" "extend_visual_line_down")
      (ls "move_visual_line_up" "extend_visual_line_up")
      (ls "move_char_right" "extend_char_right")
      (ls "move_line_down" "extend_line_down")
      (ls "move_line_up" "extend_line_up")
      (ls "move_prev_long_word_start" "extend_prev_long_word_start")
      (ls "move_next_long_word_start" "extend_next_long_word_start")
      (ls "move_prev_long_word_end" "extend_prev_long_word_end")
      (ls "move_next_long_word_end" "extend_next_long_word_end")
      (ls "move_prev_sub_word_start" "extend_prev_sub_word_start")
      (ls "move_next_sub_word_start" "extend_next_sub_word_start")
      (ls "move_prev_sub_word_end" "extend_prev_sub_word_end")
      (ls "move_next_sub_word_end" "extend_next_sub_word_end")
      (ls "move_prev_word_start" "extend_prev_word_start")
      (ls "move_next_word_start" "extend_next_word_start")
      (ls "move_prev_word_end" "extend_prev_word_end")
      (ls "move_next_word_end" "extend_next_word_end")
      (ls "move_parent_node_start" "extend_parent_node_start")
      (ls "move_parent_node_end" "extend_parent_node_end")
      (ls "goto_first_nonwhitespace" "extend_to_first_nonwhitespace")
      (ls "goto_file_start" "extend_to_file_start")
      (ls "goto_file_end" "extend_to_file_end")
      (ls "goto_line_end" "extend_to_line_end")
      (ls "goto_last_line" "extend_to_last_line")
      (ls "find_next_char" "extend_next_char")
      (ls "find_prev_char" "extend_prev_char")
      (ls "find_till_char" "extend_till_char")
      (ls "till_prev_char" "extend_till_prev_char")
      (ls "goto_word" "extend_to_word")
      (ls "goto_line_start" "extend_to_line_start")
      (ls "goto_line_end_newline" "extend_to_line_end_newline")
      (ls "search_next" "extend_search_next")
      (ls "search_prev" "extend_search_prev")
      (ls "goto_column" "extend_to_column")))
  (define (transform-command str)
    (define new-value-or-false
      (hash-try-get command-map str))
    (if (not new-value-or-false)
      str
      new-value-or-false))
  (cond
    ((string? value)
      (transform-command value))
    ((list? value)
      (map transform-command value))
    ((hash? value)
      (transduce value
        (mapping (lambda (lst)
                  (define key (list-ref lst 0))
                  (define value (list-ref lst 1))
                  (ls key (normal->select value))))
        (into-hashmap)))
    (else value)))

(define base-normal-mode
  (kv (ls "'"
       (kv (ls "'" "code_action")
         (ls 'r "rename_symbol")
         (ls 'y ":yank-diagnostic")
         (ls 's "select_references_to_symbol_under_cursor")
         (ls 'f "format_selections")
         (ls "\\" "signature_help")
         (ls '/ "hover")))
    (ls "\"" "select_register")
    (ls "@" "record_macro")
    (ls "#" "replay_macro")
    (ls '% "select_all")
    (ls '& "align_selections")
    (ls '* "search_selection_detect_word_boundaries")
    (ls 'C-* "search_selection")
    (ls "(" "rotate_selections_backward")
    (ls ")" "rotate_selections_forward")
    (ls 'minus "decrement")
    (ls '_ "trim_selections")
    (ls '= "increment")
    (ls '+ (kv (ls 'i ":toggle-option lsp.display-inlay-hints")
            (ls 'd ":toggle-option inline-diagnostics.cursor-line disable hint")
            (ls 'x ":toggle-option soft-wrap.enable")
            (ls 'm ":toggle-option auto-pairs")
            (ls '> ":toggle-option indent-guides.render")
            (ls '/ ":toggle-option search.smart-case")))
    (ls 'tab (kv (ls 'q ":buffer-close")
              (ls 'Q ":buffer-close!")
              (ls 'w ":write")
              (ls 'W ":write!")
              (ls 'R ":reload")
              (ls 't ":new")
              (ls 'p "goto_previous_buffer")
              (ls 's "goto_file")
              (ls 'f ":format")
              (ls 'n "goto_next_buffer")
              (ls "." "goto_last_modified_file")))
    (ls 'q "move_prev_word_end")
    (ls 'Q "move_prev_long_word_end")
    (ls 'C-q "move_prev_sub_word_end")
    (ls 'w "move_next_word_start")
    (ls 'W "move_next_long_word_start")
    (ls 'C-w "move_next_sub_word_start")
    (ls 'e "move_next_word_end")
    (ls 'E "move_next_long_word_end")
    (ls 'C-e "move_next_sub_word_end")
    (ls 'r "replace")
    (ls 'R "replace_with_yanked")
    (ls 'C-r (kv (ls 'minus "switch_to_lowercase")
              (ls '= "switch_to_uppercase")
              (ls 'b "switch_case")))
    (ls 't "find_till_char")
    (ls 'T "till_prev_char")
    (ls 'y "yank")
    (ls 'u "undo")
    (ls 'U "redo")
    (ls 'C-u "earlier")
    (ls 'C-U "later")
    (ls 'i "insert_mode")
    (ls 'I "insert_at_line_start")
    (ls 'o "open_below")
    (ls 'O "open_above")
    (ls 'p "paste_after")
    (ls 'P "paste_before")
    (ls "[" (kv (ls 'e "goto_prev_entry")
             (ls 't "goto_prev_class")
             (ls 'T "goto_prev_test")
             (ls 'p "goto_prev_paragraph")
             (ls "[" "goto_prev_tabstop")
             (ls 'a "goto_prev_parameter")
             (ls 'd "goto_prev_diag")
             (ls 'D "goto_first_diag")
             (ls 'f "goto_prev_function")
             (ls 'g "goto_prev_change")
             (ls 'G "goto_first_change")
             (ls 'x "goto_prev_xml_element")
             (ls 'c "goto_prev_comment")
             (ls 'space "add_newline_above")))
    (ls "]" (kv (ls 'e "goto_next_entry")
             (ls 't "goto_next_class")
             (ls 'T "goto_next_test")
             (ls 'p "goto_next_paragraph")
             (ls "]" "goto_next_tabstop")
             (ls 'a "goto_next_parameter")
             (ls 'd "goto_next_diag")
             (ls 'D "goto_last_diag")
             (ls 'f "goto_next_function")
             (ls 'g "goto_next_change")
             (ls 'G "goto_last_change")
             (ls 'x "goto_next_xml_element")
             (ls 'c "goto_next_comment")
             (ls 'space "add_newline_below")))
    (ls 'a "append_mode")
    (ls 'A "insert_at_line_end")
    (ls 's (kv (ls "(" "rotate_selection_contents_backward")
            (ls ")" "rotate_selection_contents_forward")
            (ls 'y "yank_joined")
            (ls 'p "copy_selection_on_prev_line")
            (ls 's "select_regex")
            (ls 'j "join_selections")
            (ls 'J "join_selections_space")
            (ls 'k "keep_selections")
            (ls 'K "remove_selections")
            (ls 'x "split_selection_on_newline")
            (ls 'b "reverse_selection_contents")
            (ls 'n "copy_selection_on_next_line")
            (ls 'm "merge_selections")
            (ls 'M "merge_consecutive_selections")
            (ls "," "remove_primary_selection")))
    (ls 'S "split_selection")
    (ls 'C-s (kv (ls 'i "shrink_selection")
              (ls 'I "select_all_children")
              (ls 'o "expand_selection")
              (ls 'O "select_all_siblings")
              (ls 'p "select_prev_sibling")
              (ls 'P "move_parent_node_start")
              (ls 'n "select_next_sibling")
              (ls 'N "move_parent_node_end")))
    (ls 'd "delete_selection_noyank")
    (ls 'f "find_next_char")
    (ls 'F "find_prev_char")
    (ls 'g (kv (ls 'w "goto_word")
            (ls 'r "goto_reference")
            (ls 't "goto_type_definition")
            (ls 'i "goto_implementation")
            (ls 'p "jump_backward")
            (ls 's "goto_window_center")
            (ls 'd "goto_definition")
            (ls 'D "goto_declaration")
            (ls 'g "goto_file_start")
            (ls 'h "goto_first_nonwhitespace")
            (ls 'H "goto_line_start")
            (ls 'j "move_line_down")
            (ls 'J "goto_window_bottom")
            (ls 'k "move_line_up")
            (ls 'K "goto_window_top")
            (ls 'l "goto_line_end")
            (ls 'L "goto_line_end_newline")
            (ls 'v "goto_column")
            (ls 'n "jump_forward")
            (ls "." "goto_last_modification")))
    (ls 'G "goto_last_line")
    (ls 'C-g "save_selection")
    (ls 'h "move_char_left")
    (ls 'j "move_visual_line_down")
    (ls 'J (ls "move_visual_line_down" "move_visual_line_down"))
    (ls 'k "move_visual_line_up")
    (ls 'K (ls "move_visual_line_up" "move_visual_line_up"))
    (ls 'l "move_char_right")
    (ls 'ç "flip_selections")
    (ls 'Ç "ensure_selections_forward")
    (ls 'z (kv (ls 'j "scroll_down")
            (ls 'J "align_view_top")
            (ls 'k "scroll_up")
            (ls 'K "align_view_bottom")
            (ls 's "align_view_center")
            (ls 'v "align_view_middle")))
    (ls 'x "extend_line_below")
    (ls 'X (ls "extend_line_above"))
    (ls 'C-x (ls "ensure_selections_forward" "select_line_above"))
    (ls 'C-X (ls "ensure_selections_forward" "flip_selections" "select_line_below"))
    (ls 'c "change_selection_noyank")
    (ls 'C-c "toggle_comments")
    (ls 'v "select_mode")
    (ls 'b "move_prev_word_start")
    (ls 'B "move_prev_long_word_start")
    (ls 'C-b "move_prev_sub_word_start")
    (ls 'n "search_next")
    (ls 'N "search_prev")
    (ls 'm (kv (ls 'w "@miw")
            (ls 'W "@miW")
            (ls 'C-w "@<C-w><C-b><C-e>")
            (ls 'r "surround_replace")
            (ls 'i "select_textobject_inner")
            (ls 'o "select_textobject_around")
            (ls 'a "surround_add")
            (ls 'd "surround_delete")
            (ls 'h "extend_to_first_nonwhitespace")
            (ls 'H "extend_to_line_start")
            (ls 'l "extend_to_line_end")
            (ls 'L "extend_to_line_end_newline")
            (ls 'x "extend_to_line_bounds")
            (ls 'X "shrink_to_line_bounds")
            (ls 'm "match_brackets")
            (ls "." "repeat_last_motion")))
    (ls "," "keep_primary_selection")
    (ls '< "unindent")
    (ls '> "indent")
    (ls ";" "collapse_selection")
    (ls ': "command_mode")
    (ls '/ "search")
    (ls '? "rsearch")
    (ls 'space (kv (ls 'tab "buffer_picker")
                (ls 'e "file_explorer_in_current_directory")
                (ls 'E "file_explorer")
                (ls 'C-e "file_explorer_in_current_buffer_directory")
                (ls 's "workspace_symbol_picker")
                (ls 'S "symbol_picker")
                (ls 'd "workspace_diagnostics_picker")
                (ls 'D "diagnostics_picker")
                (ls 'f "file_picker")
                (ls 'F "file_picker_in_current_directory")
                (ls 'C-f "file_picker_in_current_buffer_directory")
                (ls 'g "changed_file_picker")
                (ls 'C-g "jumplist_picker")
                (ls 'z "suspend")
                (ls ': (kv (ls 'o "@:o <C-r>%")
                        (ls 'g "@:cd <C-r>%")
                        (ls 'm "@:mv <C-r>%")
                        (ls 'M "@:mv! <C-r>%")))
                (ls '/ "global_search")
                (ls '? "command_palette")))
    (ls 'left (ls "move_char_left" "align_view_center" "align_view_middle"))
    (ls 'down (ls "move_visual_line_down" "align_view_center" "align_view_middle"))
    (ls 'S-down (ls "move_visual_line_down" "move_visual_line_down" "align_view_center" "align_view_middle"))
    (ls 'up (ls "move_visual_line_up" "align_view_center" "align_view_middle"))
    (ls 'S-up (ls "move_visual_line_up" "move_visual_line_up" "align_view_center" "align_view_middle"))
    (ls 'right (ls "move_char_right" "align_view_center" "align_view_middle"))
    (ls 'ret (kv (ls 'q "wclose")
              (ls 'ret "rotate_view")
              (ls 'o "wonly")
              (ls 'x "hsplit")
              (ls 'h "jump_view_left")
              (ls 'H "swap_view_left")
              (ls 'j "jump_view_down")
              (ls 'J "swap_view_down")
              (ls 'k "jump_view_up")
              (ls 'K "swap_view_up")
              (ls 'l "jump_view_right")
              (ls 'L "swap_view_right")
              (ls 'y "vsplit")))
    (ls 'S-ret "rotate_view_reverse")))

(define normal-mode
  (hash-union base-normal-mode
    (kv (ls 'H (ls "move_prev_sub_word_start" "collapse_selection"))
      (ls 'L (ls "move_next_sub_word_end" "collapse_selection"))
      (ls 'S-left (ls "move_prev_sub_word_start" "collapse_selection" "align_view_center" "align_view_middle"))
      (ls 'S-right (ls "move_next_sub_word_end" "collapse_selection" "align_view_center" "align_view_middle")))))

(define select-mode
  (hash-union (normal->select base-normal-mode)
    (kv (ls 'esc "normal_mode")
      (ls 'H "extend_prev_sub_word_start")
      (ls 'L "extend_next_sub_word_end")
      (ls 'left (ls "move_char_left" "align_view_center" "align_view_middle"))
      (ls 'S-left (ls "extend_prev_sub_word_start" "align_view_center" "align_view_middle"))
      (ls 'down (ls "extend_visual_line_down" "align_view_center" "align_view_middle"))
      (ls 'S-down (ls "extend_visual_line_down" "extend_visual_line_down" "align_view_center" "align_view_middle"))
      (ls 'up (ls "extend_visual_line_up" "align_view_center" "align_view_middle"))
      (ls 'S-up (ls "extend_visual_line_up" "extend_visual_line_up" "align_view_center" "align_view_middle"))
      (ls 'right (ls "extend_char_right" "align_view_center" "align_view_middle"))
      (ls 'S-right (ls "extend_next_sub_word_end" "align_view_center" "align_view_middle")))))

(define insert-mode
  (kv (ls 'esc "normal_mode")
    (ls 'tab "smart_tab")
    (ls 'S-tab "insert_tab")
    (ls 'C-r "insert_register")
    (ls 'C-u "commit_undo_checkpoint")
    (ls 'C-d "delete_char_forward")
    (ls 'C-D "delete_word_forward")
    (ls "C-\\" "signature_help")
    (ls 'C-x "completion")
    (ls 'C-/ "hover")
    (ls 'ret "insert_newline")
    (ls 'S-ret "insert_newline")
    (ls 'left (ls "move_char_left" "align_view_center" "align_view_middle"))
    (ls 'S-left (ls "move_prev_sub_word_start" "collapse_selection" "align_view_center" "align_view_middle"))
    (ls 'down (ls "move_visual_line_down" "align_view_center" "align_view_middle"))
    (ls 'S-down (ls "move_visual_line_down" "move_visual_line_down" "align_view_center" "align_view_middle"))
    (ls 'up (ls "move_visual_line_up" "align_view_center" "align_view_middle"))
    (ls 'S-up (ls "move_visual_line_up" "move_visual_line_up" "align_view_center" "align_view_middle"))
    (ls 'right (ls "move_char_right" "align_view_center" "align_view_middle"))
    (ls 'S-right (ls "move_next_sub_word_end" "collapse_selection" "align_view_center" "align_view_middle"))
    (ls 'backspace "delete_char_backward")
    (ls 'S-backspace "delete_char_backward")))

(define keybindings
  (kv (ls 'normal normal-mode)
    (ls 'insert insert-mode)
    (ls 'select select-mode)))

(hx.cfg.set-keybindings!
  (~> keybindings
    (value->jsexpr-string)
    (hx.core.keymaps.helix-string->keymap)))

