wayland_enable_ime no

font_size 7.5
disable_ligatures always
underline_exclusion 0

cursor_shape beam
cursor_blink_interval 0.3
cursor_trail 3
cursor_trail_decay 0.1 0.4

scrollback_lines 5000
scrollback_pager_history_size 100

show_hyperlink_targets yes

repaint_delay 15

tab_bar_edge top
tab_bar_style powerline
tab_powerline_style slanted
tab_bar_align left
tab_bar_min_tabs 1
active_tab_font_style normal

enabled_layouts fat:bias=66,stack
draw_minimal_borders no
draw_window_borders_for_single_window yes
window_margin_width 1.5

background_opacity 0.95

allow_remote_control yes

map alt+f5            load_config_file
map alt+minus         resize_window narrower
map alt+shift+minus   resize_window shorter
map ctrl+alt+minus    change_font_size all -0.5
map alt+equal         resize_window wider
map alt+plus          resize_window taller
map ctrl+alt+equal    change_font_size all +0.5
map alt+q             close_window_with_confirmation ignore-shell
map alt+shift+q       close_tab
map alt+e             launch --stdin-source=@screen_scrollback ${EDITOR}
map alt+r             set_window_title
map alt+shift+r       set_tab_title
map alt+u             scroll_line_up
map alt+shift+u       scroll_to_prompt -1
map alt+p             previous_tab
map alt+shift+p       kitten kittens/smart_detach.py left
map alt+d             scroll_line_down
map alt+shift+d       scroll_to_prompt 1
map alt+h             neighboring_window left
map alt+shift+h       move_window left
map alt+j             neighboring_window bottom
map alt+shift+j       move_window bottom
map alt+k             neighboring_window top
map alt+shift+k       move_window top
map alt+l             neighboring_window right
map alt+shift+l       move_window right
map alt+z             toggle_layout stack
map ctrl+alt+c        copy_to_clipboard
map ctrl+alt+v        paste_from_clipboard
map alt+n             next_tab
map alt+shift+n       kitten kittens/smart_detach.py right
map alt+t             new_window
map alt+shift+t       new_tab
