name: Check partial branch on push and attempt to promote to master
on:
  push:
    branches: [partial]
jobs:
  test-and-promote:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ secrets.GITHUB_TOKEN }}
      - uses: DeterminateSystems/determinate-nix-action@v3
        with:
          extra-conf: |
            accept-flake-config = true
      - env:
          GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}
        run: |
          nix profile add nixpkgs#geminicommit
          gmc config set api.key $GEMINI_API_KEY

          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

          git fetch origin master
          git switch master

          for sha in $(git log --reverse --format="%H" master..partial); do
            git cherry-pick --no-commit $sha

            if nix flake check 2>&1; then
              gmc --no-verify
              git push origin master
            fi
          done
